### ISSUE TITLE
Ampliación de posibilidades de cambio de propiedades

### ISSUE THREAD

**Issue by JeremiasCastroL** [Dsgnr-JM/bell#1]
Seria muy bueno,  que el usuario pudiera cambiar más propiedades de las alertas, como su tamaño,  el tipo de letra, el border radius.

**Comment by Dsgnr-JM** [comment]
Si ya muchas devs me han pedido dichas funcionalidades, varias ya an sido agregadas a la version 2.0 y veran la luz pronto.

**Comment by Dsgnr-JM** [comment]
Gracias por tu feedback la version 2 de Bell ya esta aqui
